In [4]:
import numpy as np
import os
import sys
import matplotlib.pyplot as plt
import cv2
import glob

In [31]:
img =cv2.imread('./test/fig/puppy.bmp')
if img is None:
    print('1')
    sys.exit()
    
img[h//2-100:h//2+50, w//2-100:w//2+200]=(0,0,0)
cv2.imshow('1',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
## 중앙의 픽셀값을 골라보기

h,w = img.shape[:2]
point1 = img[h//2:h//2+3,w//2:w//2+3]

In [15]:
print('image center value',point1) ##B,G,R 순서 ## 사진에서 3x3의 픽셀 값을 뽑아낼 수 있다.


image center value [[[  0  14  40]
  [ 25  39  62]
  [ 26  39  65]]

 [[  1  14  40]
  [ 34  48  70]
  [ 57  71  95]]

 [[ 61  74  98]
  [ 94 108 130]
  [100 114 137]]]


In [17]:
img[10:100, 50:200] =(0,0,255)  ## 세로방향 가로 방향 브로드 케스팅에 의해서 하나만 넣어도 3개다 바뀜

In [52]:
## 판넬 만들기
## 위의 img1 img2는 많이 쓰임
img1 = np.ones((600,1000,3), dtype=np.uint8)*255 #가로 600 세로 1000 
img2 = np.zeros((600,1000), dtype=np.uint8)## 흑백
img3 = np.full((600,1000,3), (0,255,255), np.uint8) ## 색넣기
img4 =np.random.randint(0,255, (600,1000),np.uint8) ## 노이즈 만들기


cv2.imshow('V',img2)
cv2.waitKey()
cv2.destroyAllWindows()



In [68]:
## 영상복사
img = cv2.imread('./test/fig/fig/mask_plane.bmp')
if img is None:
    print('1')
    sys.exit()
img1 = img ## 주소를 카피하는것.
img2 = img.copy() ## 실제 데이터를 카피하여  문제 발생을 없앤다 딥 카피라고 불린다.
img1[40:80,100:200] =(255,0,255) ## call by reference 문제 발생 

cv2.imshow('original',img)
cv2.imshow('2',img1)
cv2.imshow('3',img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [97]:
img = cv2.imread('./test/fig/puppy.bmp')
if img is None:
    print('1')
    sys.exit()
img1 = img[200:400, 300:500] ## 부분 CALL BY REPERENCE
img2 = img[200:400, 300:500].copy() 
cv2.circle(img2,(100,100),100,(0,0,255),8,cv2.LINE_AA)
cv2.imshow('original',img)
cv2.imshow('1',img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [129]:
img = cv2.imread('./test/fig/fig/rudolf.png')
if img is None:
    print('1')
    sys.exit()

h,w =img.shape[:2]
img1 = img[h//2-60:h//2+80,w//2-80:w//2+100]
cv2.circle(img1,(90,85),65,(0,0,225),-1,cv2.LINE_AA)
cv2.imshow('1', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [149]:
src = cv2.imread('./test/fig/fig/airplane.bmp')
mask = cv2.imread('./test/fig/fig/mask_plane.bmp',0)
dst = cv2.imread('./test/fig/fig/field.bmp')

cv2.copyTo(src,mask,dst)           #mask 는 내가 관심있는 영역이 1인 binary 이미지
cv2.imshow('src',src)
cv2.imshow('mask',mask)
cv2.imshow('dst',dst)

cv2.waitKey()
cv2.destroyAllWindows()

In [139]:
print('src shape=',src.shape)
print('mask shape=',mask.shape)
print('dst shape=',dst.shape)

src shape= (400, 600, 3)
mask shape= (400, 600)
dst shape= (400, 600, 3)


In [151]:
src = cv2.imread('./test/fig/fig/cow.png')
dst = cv2.imread('./test/fig/fig/green.png')
if src is None or dst is None:
    print('1')
    sys.exit()

cv2.imshow('src',src)
cv2.imshow('dst',dst)

cv2.waitKey()
cv2.destroyAllWindows()

In [145]:
h,w =src.shape[:2]

In [163]:
dst_resize =cv2.resize(dst, (w,h))
src_gray = cv2.cvtColor(src,cv2.COLOR_BGR2GRAY)
_,mask = cv2.threshold(src_gray, 240,255, cv2.THRESH_BINARY_INV)

cv2.copyTo(src,mask,dst_resize)
cv2.imshow('1',dst_resize)

cv2.waitKey()
cv2.destroyAllWindows()