In [46]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.models import Sequential
import numpy as np

In [1]:
text = '해보지 않으면 해낼 수 없다'
print('text:', text_to_word_sequence(text))

text: ['해보지', '않으면', '해낼', '수', '없다']


In [9]:
docs = [' 먼저 텍스트의 각 단어를 토큰화 합니다',
       '텍스트의 단어로 토큰화 해서 딥러닝에서 인식 됩니다',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다']

token = Tokenizer()

token.fit_on_texts(docs)

print(token.word_counts)
print(token.document_count)
print(token.word_docs)
print(token.word_index)



OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('토큰화', 2), ('합니다', 1), ('단어로', 1), ('해서', 1), ('딥러닝에서', 2), ('인식', 1), ('됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])
3
defaultdict(<class 'int'>, {'단어를': 1, '합니다': 1, '텍스트의': 2, '먼저': 1, '각': 1, '토큰화': 2, '딥러닝에서': 2, '됩니다': 1, '해서': 1, '단어로': 1, '인식': 1, '결과는': 1, '있습니다': 1, '수': 1, '사용할': 1, '토큰화한': 1})
{'텍스트의': 1, '토큰화': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '합니다': 7, '단어로': 8, '해서': 9, '인식': 10, '됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


In [10]:
print(docs)

[' 먼저 텍스트의 각 단어를 토큰화 합니다', '텍스트의 단어로 토큰화 해서 딥러닝에서 인식 됩니다', '토큰화한 결과는 딥러닝에서 사용할 수 있습니다']


In [17]:
def word_counts(docs):
    results = {}
    for sentence in docs:
        words = sentence.split(' ')
        for word in words:
            if word in results:
                results[word] +=1
            else:
                results[word] = 1
    return results

results = word_counts(docs)
for word,cnt in results.items():
    print(word ,":", cnt)
        
    

 : 1
먼저 : 1
텍스트의 : 2
각 : 1
단어를 : 1
토큰화 : 2
합니다 : 1
단어로 : 1
해서 : 1
딥러닝에서 : 2
인식 : 1
됩니다 : 1
토큰화한 : 1
결과는 : 1
사용할 : 1
수 : 1
있습니다 : 1


In [16]:
word_counts(docs)

{'': 1,
 '먼저': 1,
 '텍스트의': 2,
 '각': 1,
 '단어를': 1,
 '토큰화': 2,
 '합니다': 1,
 '단어로': 1,
 '해서': 1,
 '딥러닝에서': 2,
 '인식': 1,
 '됩니다': 1,
 '토큰화한': 1,
 '결과는': 1,
 '사용할': 1,
 '수': 1,
 '있습니다': 1}

In [19]:
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token = Tokenizer()
token.fit_on_texts([text])

print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [24]:
x =token.texts_to_sequences([text])

In [29]:
to_categorical(x, num_classes=len(x[0])+1)

array([[[0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]]], dtype=float32)

In [32]:
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요",
        "추천하고 싶은 영화입니다","한번 더 보고싶네요",
        "글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

In [34]:
classes = np.array([1,1,1,1,1,0,0,0,0,0])

In [37]:
token =Tokenizer()

token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [39]:
x =token.texts_to_sequences(docs)

In [41]:
padded_x = pad_sequences(x,4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [43]:
word_size = len(token.word_index)+1


In [49]:
model= Sequential()
model.add(Embedding(word_size, 8,input_length=4 ))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [50]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 1s 506ms/step - loss: 0.7020 - accuracy: 0.3000
Epoch 2/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6999 - accuracy: 0.3000
Epoch 3/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6978 - accuracy: 0.3000
Epoch 4/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6957 - accuracy: 0.3000
Epoch 5/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6936 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6916 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6895 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6874 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6854 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6833 - accuracy: 0.8000
Epoch 11/20
1/1 [====================

In [51]:
print(model.evaluate(padded_x,classes)[1])

1/1 [==============================] - 0s 128ms/step - loss: 0.6608 - accuracy: 0.9000
0.8999999761581421


In [53]:
model.predict(padded_x[-1].reshape(1,-1))

1/1 [==============================] - 0s 80ms/step


array([[0.47958335]], dtype=float32)