<a href="https://colab.research.google.com/github/mch60131242/Home/blob/main/%ED%8A%B8%EB%A6%AC%EC%9D%98_%EC%95%99%EC%83%81%EB%B8%94_%EA%B8%B0%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
# 무한히 표본을 뽑아 평균을 내면 그 평균은 결국  모집단의 평균을 따르게 된다 


In [18]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol','sugar','pH']].to_numpy()
target=wine['class'].to_numpy()
train_input, test_input, train_target, test_target = train_test_split(data,target, test_size=0.2, random_state=42)

In [19]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf,train_input,train_target, return_train_score= True, n_jobs=-1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.9973541965122431 0.8905151032797809


In [20]:
rf.fit(train_input,train_target)
print(rf.feature_importances_) ## 특성 중요도 확인

[0.23167441 0.50039841 0.26792718]


In [21]:
rf=RandomForestClassifier(oob_score=True, n_jobs = -1 , random_state=42)
rf.fit(train_input,train_target)
print(rf.oob_score_)

0.8934000384837406


In [22]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1 , random_state=42)
scores = cross_validate(et, train_input, train_target,
                        return_train_score = True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974503966084433 0.8887848893166506


In [23]:
et.fit(train_input,train_target)
print(et.feature_importances_)## 특성 중요도 확인

[0.20183568 0.52242907 0.27573525]


In [25]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state =42)
scores = cross_validate(gb, train_input, train_target,
                        return_train_score = True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8881086892152563 0.8720430147331015


In [37]:
gb = GradientBoostingClassifier(n_estimators= 500, learning_rate=0.2,random_state =42)
scores = cross_validate(gb, train_input, train_target,
                        return_train_score = True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))## 학습점수가 테스트 점수에 비해 너무 높아 과적합 패턴이 의심된다.

0.9464595437171814 0.8780082549788999


In [32]:
gb.fit(train_input,train_target)
print(gb.feature_importances_)

[0.14230296 0.70606994 0.1516271 ]


In [39]:
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input , train_target,
                        return_train_score= True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))  

0.9321723946453317 0.8801241948619236


In [42]:
from sklearn.inspection import permutation_importance
hgb.fit(train_input,train_target)
result = permutation_importance(hgb, train_input , train_target,
                        n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean)


[0.08876275 0.23438522 0.08027708]


In [44]:
result = permutation_importance(hgb, test_input , test_target,
                        n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean, result.importances_std)

[0.05969231 0.20238462 0.049     ] [0.004      0.007938   0.00453846]


In [45]:
hgb.score(test_input,test_target)

0.8723076923076923

In [53]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42,n_jobs=-1)
scores =cross_validate(xgb, train_input, train_target, return_train_score=True,)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))  

0.9555033709953124 0.8799326275264677


In [52]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(tree_method='hist', random_state=42, n_jobs=-1)
scores =cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))  

0.9338079582727165 0.8789710890649293
